# This is a basic workflow to help you get started with Actions
# Give a name to the workflow (Name of the workflow)

# .github/workflows/blank.yml
name: On-Workflow-Dispatch

# When the workflow should trigger. Trigger event (push, pull request, schedule, manual)
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel. In a workflow we can have multiple jobs
jobs:
  # This workflow contains a single job called "build". job_name-1 is the name of the job
  job_name-1:
    # The type of runner that the job will run on. Where the job should run. This is called defining the runner
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v4

      # Runs a single command using the runners shell. Name of the step and what this step should do
      - name: Run a one-line script
        run: echo "Workflow Executed successfully!!!"

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
