name: Context Variable Demo
on: push
jobs:
  context-variable-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Use Context Variables
        run: |
          echo "This workflow is triggered by - ${{github.actor}}"
          echo "The repository name is - ${{github.repository}}"
          echo "$GITHUB_SHA"


# Printing Context & Environment Variable
# echo "The repository name is - ${{github.repository}}" => This is a GitHub Context, so we use the context iside the {{}} curly brases
# echo "$GITHUB_SHA" => This is an environment variable so we $ sign and followed the variable name

# Note: Reference URL:  https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#github-context
#    - name: Print all variables under GitHub
#      run: echo "${{toJson(github)}}"
