name: Inputs Demo
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: Choose the Environment to Deploy
        required: true
        default: Dev Environment      # default input parameter value is given
        type: choice                  # input option type given as choice (this is optional, if you want to give as choice, under options give the choices)
        options:
          - development
          - test
          - production
      artifact_tag:
        description: Choose the Git Tag    # second input parameter given for use to to provide manual input
        
jobs:
  inputs_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the application
        run: echo "Deploying the ${{inputs.artifact_tag}} Application to - ${{inputs.environment}}"
        
