name: Outputs-Demo2-PUSH
on: push
jobs:
  job_build:
    outputs:
      version: ${{steps.step1.outputs.version}}
    runs-on: ubuntu-latest
    steps:
      - name: build_steps
        id: step1
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT

  job2_deploy:
    needs: job_build
    runs-on: ubuntu latest
    steps:
      - name: deploy_steps
        run: echo "We are deploying the applicatio with version is ${{ needs.job_build.outputs.version}}"
